
all:
#	@cd vo;      make
#	@cd vio;     make
#	@cd audio;   make
#	@cd awb_online_calibration; make
#	@cd hifb;    make
#	@cd lsc_online_cali; make
#	@cd region;    make
#	@cd tde;     make
#	@cd venc;    make
#	@cd ive;     make
#	@cd ivp;     make
#	@cd uvc_app; make
#	@cd scene_auto; make
#	@cd ir_auto; make
	@cd yjsnpi; make
clean:
	@cd vo;      make clean
	@cd vio;     make clean
	@cd audio;   make clean
	@cd awb_online_calibration; make clean
	@cd hifb;    make clean
	@cd lsc_online_cali; make clean
	@cd region;  make clean
	@cd tde;     make clean
	@cd venc;    make clean
	@cd ive;     make clean
	@cd ivp;     make clean
	@cd uvc_app; make clean
	@cd scene_auto; make clean
	@cd ir_auto;make clean
	@cd yjsnpi; make clean	
